[theme]
base            = "dark"
primaryColor    = "#00c853"
backgroundColor = "#0a1622"
secondaryBackgroundColor = "#0f2231"
textColor       = "#e9f3fc"
font            = "sans serif"

[client]
toolbarMode = "viewer"
showErrorDetails = "none"
showErrorLinks = false

[server]
headless = true
enableCORS = false
